export ENV_STORE="$KEEPSAKE_SCRIPTS_ROOT/.env.versions"
export TAG="${TAG:-$(date +"%Y%m%d-%H%M")}"
export DEFAULT_IMAGE_TAG="${DEFAULT_IMAGE_TAG:-latest}"
export COLOR_GREEN="${COLOR_GREEN:-\033[0;32m}"
export TEST_DIRECTORY="${TEST_DIRECTORY:-tests}"
export PYTHON_VERSION="${PYTHON_VERSION:-python3.10}"
export PROJECT_VENV_DIR="${PROJECT_VENV_DIR:-.venv}"
export PROJECT_JUPYTER_VENV_DIR="${PROJECT_JUPYTER_VENV_DIR:-.jupyter_venv}"
export PYPI_HOST=localhost
export PYPI_PORT=8300
export PYPI_USERNAME=admin
export PYPI_PASSWORD=your-secret-password
