export ENV_STORE="$KEEPSAKE_SCRIPTS_ROOT/.env.versions"
export TAG="${TAG:-$(date +"%Y%m%d-%H%M")}"
export DEFAULT_IMAGE_TAG="${DEFAULT_IMAGE_TAG:-latest}"
export COLOR_GREEN="${COLOR_GREEN:-\033[0;32m}"
export TEST_DIRECTORY="${TEST_DIRECTORY:-tests}"
export PYTHON_VERSION="${PYTHON_VERSION:-python3.10}"
export PROJECT_VENV_DIR="${PROJECT_VENV_DIR:-.venv}"
export PROJECT_JUPYTER_VENV_DIR="${PROJECT_JUPYTER_VENV_DIR:-.jupyter_venv}"

# Pinned DEV service ports (documentation + shared defaults)
export KEEPSAKE_BACKEND_PORT="${KEEPSAKE_BACKEND_PORT:-31325}"
export KEEPSAKE_FRONTEND_PORT="${KEEPSAKE_FRONTEND_PORT:-32686}"
export KEEPSAKE_PYPI_PORT="${KEEPSAKE_PYPI_PORT:-31126}"
export KEEPSAKE_MEMORY_GRAPH_PORT="${KEEPSAKE_MEMORY_GRAPH_PORT:-31605}"
export KEEPSAKE_LANGGRAPH_PORT="${KEEPSAKE_LANGGRAPH_PORT:-31224}"
export KEEPSAKE_BRAIN_VIEWER_PORT="${KEEPSAKE_BRAIN_VIEWER_PORT:-32196}"

export KEEPSAKE_BACKEND_URL="http://localhost:${KEEPSAKE_BACKEND_PORT}"
export KEEPSAKE_FRONTEND_URL="http://localhost:${KEEPSAKE_FRONTEND_PORT}"
export KEEPSAKE_MEMORY_GRAPH_URL="http://localhost:${KEEPSAKE_MEMORY_GRAPH_PORT}"
export KEEPSAKE_LANGGRAPH_URL="http://localhost:${KEEPSAKE_LANGGRAPH_PORT}"
export KEEPSAKE_BRAIN_VIEWER_URL="http://localhost:${KEEPSAKE_BRAIN_VIEWER_PORT}"

export KEEPSAKE_API_URL="${KEEPSAKE_BACKEND_URL}/api"
export KEEPSAKE_API_V1_URL="${KEEPSAKE_BACKEND_URL}/api/v1"

# PyPI configuration - prefer pinned DEV port if available
PYPI_HOST="${PYPI_HOST:-localhost}"
PYPI_PORT="${PYPI_PORT:-${KEEPSAKE_PYPI_PORT:-31126}}"
PYPI_USERNAME="${PYPI_USERNAME:-admin}"
PYPI_PASSWORD="${PYPI_PASSWORD:-your-secret-password}"

# Derived URL for convenience
export PYPI_URL="http://${PYPI_HOST}:${PYPI_PORT}"
